projects:
  neighborgoods:
    schemaPath: ./src/schemas/schema.graphql
    extensions:
      endpoints:
        dev: 'http://localhost:5000/graphql'
        subscription: "ws://localhost:5000/graphql"
