version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      # Perhaps consider PORT binding
      - 5432
    volumes:
      - "./dumps:/dumps"
      - db-postgres:/var/opt/postgres
  redis:
    image: redis:5.0.4
    ports:
      - 6379:6379
      - 6370:6370
    volumes:
      - redis-data:/data
volumes:
  db-postgres:
  redis-data:
